const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
global.crypto=require('crypto').webcrypto;
const MathCore=require(path.join(root,'math-core-v17.js'));
const Risk=require(path.join(root,'risk-engine-v17.js'));
const profile=MathCore.normalizeProfile({rtp:.50,maxMultiplier:999,testMode:false});
assert.strictEqual(profile.rtp,.95,'production RTP must remain locked at 95%');
assert(Math.abs(profile.houseEdge-.05)<1e-12,'production house edge must remain locked at 5%');
assert.strictEqual(profile.profileId,'RCB-GLOBAL-95');
assert.strictEqual(profile.maxMultiplier,100);
for(const u of [0,.001,.01,.5,.9,.99,.999999])assert(MathCore.bustFromUniform(u,profile)>=1);
assert.throws(()=>MathCore.bustFromUniform(-.01,profile));
assert.throws(()=>MathCore.bustFromUniform(1,profile));
const config={minBet:1,maxBet:500,maxMultiplier:100,maxPayoutPerBet:50000,maxPayoutPerRound:150000,maxSessionExposure:250000,reserveTargetAmount:100000,usableReservePct:.5,liabilityCoverageEnabled:true,criticalCoverage:1.05};
const finance={houseCash:10000,reserveBalance:100000,openExposure:0,roundExposure:0,sessionExposure:0};
assert(['ALLOW','LIMIT'].includes(Risk.evaluateBet({stake:10,maxCashout:10,finance,config}).decision));
const core=fs.readFileSync(path.join(root,'core-v17.js'),'utf8');
const player=fs.readFileSync(path.join(root,'index.html'),'utf8');
const admin=fs.readFileSync(path.join(root,'admin.html'),'utf8');
for(const token of ['sessionHorizonRounds:10000','SESSION_CLOSED','MathCore.generateBust(state.config.mathProfile)','autoCashout','balanceBefore'])assert(core.includes(token),'core missing '+token);
assert(!core.includes('effectiveRtp'),'treasury must not adapt RNG/RTP');
for(const token of ['const [send,listen]=room.makeAction','actions.state.listen','room.onPeerJoin(','target||undefined'])assert(core.includes(token),'core sync API missing '+token);
for(const forbidden of ['.onMessage=','room.onPeerJoin=','target?{target}'])assert(!core.includes(forbidden),'core contains obsolete Trystero API '+forbidden);
for(const token of ['data-lang="az"','data-lang="ru"','data-lang="en"','RCB-GLOBAL-95','95% theoretical RTP','data-open-admin','data-admin-frame','data-open-audit','data-mode="auto"','data-auto-rounds','v1.10.0 SYNC','function animateFlight()','requestAnimationFrame(animateFlight)','data-countdown-box','data-open-deposit','data-deposit-submit','RocketCrashBest.setWallet(next)'])assert(player.includes(token),'player missing '+token);
for(const forbidden of ['House Cash','Open Exposure','Reserve Target','Critical Coverage'])assert(!player.includes(forbidden),'player exposes admin field '+forbidden);
for(const token of ['ACTIVE / MAIN','sessionHorizonRounds','100000000','95.00%','5.00%'])assert(admin.includes(token),'admin missing '+token);
console.log('Rocket Crash Best v1.10 architecture/UI/sync QA PASS');
