(()=>{'use strict';
const META={"name":"Greyhound Rush","prefix":"greyhoundrushv2lc","config":"greyhoundrushv2lc_config_v2","finance":"greyhoundrushv2lc_finance_v2","metrics":"greyhoundrushv2lc_metrics_v2","logs":"greyhoundrushv2lc_logs_v2","lang":"greyhoundrushv2lc_lang_v2","reset":"greyhoundrushv2lc_reset_v2","reserve":"reserveBalance","exposure":"openExposure"};
const IS_ADMIN=/\/admin\.html(?:$|\?)/i.test(location.pathname+location.search);
const ID=(crypto?.randomUUID?.()||('tab-'+Date.now()+'-'+Math.random())).replace(/[^a-zA-Z0-9_.-]/g,'');
const K={presence:META.prefix+'_player_presence_v25',lock:META.prefix+'_admin_engine_lock_v25',clock:META.prefix+'_engine_clock_v25',last:META.prefix+'_engine_last_round_v25'};
const BASE_RUN_MS=3400,LEASE_MS=2600,PLAYER_FRESH_MS=1800;
function roundMs(c){return Math.max(2600,Math.round(BASE_RUN_MS+Math.max(300,num(c?.countdownMs,1800))))}
const read=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const rnd=()=>{if(globalThis.crypto?.getRandomValues){const a=new Uint32Array(1);crypto.getRandomValues(a);return(a[0]+1)/4294967297}return Math.random()||Number.EPSILON};
const money=n=>Math.round((Number(n)||0)*100)/100;
function cfg(){const c=read(META.config,{});const margin=clamp(num(c.targetProfitMargin,1-num(c.targetRtp,.5)),.01,.95);c.targetProfitMargin=margin;c.targetRtp=1-margin;c.payoutBudgetPct=clamp(num(c.payoutBudgetPct,.5),.05,1);c.reserveTargetAmount=Math.max(0,num(c.reserveTargetAmount,c.reserveInitialAmount??20000));c.usableReservePct=clamp(num(c.usableReservePct,1),0,1);c.reserveRestorePct=clamp(num(c.reserveRestorePct,.25),0,1);c.maxBet=Math.max(1,num(c.maxBet,500));c.minBet=Math.max(.01,num(c.minBet,1));c.maxMultiplier=Math.max(2,num(c.maxMultiplier,100));c.maxPayoutPerBet=Math.max(c.minBet,num(c.maxPayoutPerBet,50000));c.maxPayoutPerRound=Math.max(c.maxPayoutPerBet,num(c.maxPayoutPerRound,150000));c.maxSessionExposure=Math.max(c.maxPayoutPerRound,num(c.maxSessionExposure,250000));c.liabilityCoverageEnabled=c.liabilityCoverageEnabled!==false;c.riskThresholds=Object.assign({warningCoverage:2,stressCoverage:1.35,criticalCoverage:1.05},c.riskThresholds||{});c.riskPressure=Object.assign({reserveWeight:.45,marginWeight:.35,budgetWeight:.20,coverageWeight:.35,maxRtpReduction:.70},c.riskPressure||{});return c}
function finance(c){const f=read(META.finance,{});f.houseCash=Math.max(0,num(f.houseCash,0));let rb=num(f[META.reserve],NaN);if(!Number.isFinite(rb))rb=num(f.reserveBalance,NaN);if(!Number.isFinite(rb))rb=num(f.reserve,NaN);if(!Number.isFinite(rb))rb=c.reserveTargetAmount;f.reserveBalance=Math.max(0,rb);f.reserve=Math.max(0,rb);f.reserveTarget=c.reserveTargetAmount;f.totalStake=Math.max(0,num(f.totalStake,0));f.totalPayout=Math.max(0,num(f.totalPayout,0));f.rounds=Math.max(0,Math.floor(num(f.rounds,0)));f.openExposure=Math.max(0,num(f.openExposure??f.openLiability,0));f.openLiability=f.openExposure;f.reserveUsed=Math.max(0,num(f.reserveUsed,0));f.reserveRestored=Math.max(0,num(f.reserveRestored,0));return f}
function saveFinance(f){f[META.reserve]=money(f.reserveBalance);f.reserve=money(f.reserveBalance);f.reserveBalance=money(f.reserveBalance);f[META.exposure]=money(f.openExposure);f.openExposure=money(f.openExposure);f.openLiability=money(f.openExposure);write(META.finance,f)}
function snap(c,f,extra=0){const target=c.reserveTargetAmount,balance=f.reserveBalance,reserveHealth=target?clamp(balance/target,0,1):1,profit=f.totalStake-f.totalPayout,actualMargin=f.totalStake?profit/f.totalStake:c.targetProfitMargin,handle=Math.min(1,f.totalStake/5000),marginDeficit=Math.max(0,c.targetProfitMargin-actualMargin),marginPressure=Math.min(1,(marginDeficit/Math.max(.08,c.targetProfitMargin*.5))*handle),budget=Math.max(0,f.houseCash*c.payoutBudgetPct),exposure=Math.max(0,f.openExposure+extra),budgetPressure=exposure?clamp(1-budget/exposure,0,1):0,reservePressure=1-reserveHealth,rp=c.riskPressure,base=clamp(reservePressure*rp.reserveWeight+marginPressure*rp.marginWeight+budgetPressure*rp.budgetWeight,0,1),liq=f.houseCash+balance*c.usableReservePct,coverage=exposure?liq/exposure:999;let cp=0;if(c.liabilityCoverageEnabled&&exposure){const w=Math.max(num(c.riskThresholds.warningCoverage,2),num(c.riskThresholds.criticalCoverage,1.05)+.01),cr=Math.max(.01,num(c.riskThresholds.criticalCoverage,1.05));if(coverage<=cr)cp=1;else if(coverage<w)cp=clamp((w-coverage)/(w-cr),0,1)}const pressure=clamp(base+(c.liabilityCoverageEnabled?cp*num(rp.coverageWeight,.35)*(1-base):0),0,1),effectiveRtp=Math.max(.05,c.targetRtp*(1-pressure*num(rp.maxRtpReduction,.70)));return{pressure,effectiveRtp,coverage,liq,budget,actualMargin,reserveHealth}}
function bust(c,f){const s=snap(c,f),u=rnd();let x=s.effectiveRtp/(1-u);x=clamp(x,1,c.maxMultiplier);if(s.pressure>.35&&x<1.01)x=Math.min(c.maxMultiplier,1.01+rnd()*(.11-.06*s.pressure));return Math.floor(x*100)/100}
function targets(pressure){return pressure>=.7?[1.05,1.08,1.10,1.12,1.18,1.25,1.35]:pressure>=.4?[1.05,1.10,1.15,1.20,1.30,1.50,1.80,2.00]:[1.05,1.10,1.20,1.30,1.50,1.80,2,2.5,3,5,8]}
function runRound(catchup=false){const c=cfg(),f=finance(c),pre=snap(c,f),ts=targets(pre.pressure),stakes=[1,2,5,10,10,20,25,50,100],count=20+Math.floor(rnd()*31),bets=[];let liability=0,roundStake=0;for(let i=0;i<count;i++){const target=ts[Math.floor(rnd()*ts.length)],baseStake=stakes[Math.floor(rnd()*stakes.length)],hardCap=Math.min(c.maxBet,c.maxPayoutPerBet/target,(c.maxPayoutPerRound-liability)/target,(c.maxSessionExposure-liability)/target);let st=Math.min(baseStake,hardCap);if(st<c.minBet)continue;st=money(st);const li=money(st*target),next=liability+li;if(c.liabilityCoverageEnabled){const futureHouse=f.houseCash+roundStake+st,futureLiq=futureHouse+f.reserveBalance*c.usableReservePct,critical=Math.max(.01,num(c.riskThresholds.criticalCoverage,1.05));if(futureLiq/Math.max(1,next)<critical)continue}liability=next;roundStake+=st;bets.push({stake:st,target})}
if(!bets.length){const target=1.05,st=Math.max(c.minBet,Math.min(2,c.maxBet,c.maxPayoutPerBet/target));if(st>=c.minBet){bets.push({stake:money(st),target});roundStake=money(st);liability=money(st*target)}}
f.houseCash=money(f.houseCash+roundStake);f.totalStake=money(f.totalStake+roundStake);f.openExposure=money(liability);saveFinance(f);
const b=bust(c,f);let requested=0,paid=0,wins=0,losses=0;for(const bet of bets){if(b>bet.target){requested+=Math.min(bet.stake*bet.target,c.maxPayoutPerBet);wins++}else losses++}requested=money(Math.min(requested,c.maxPayoutPerRound));let due=requested,fromHouse=Math.min(f.houseCash,due);f.houseCash=money(f.houseCash-fromHouse);due=money(due-fromHouse);let fromReserve=Math.min(f.reserveBalance*c.usableReservePct,due);f.reserveBalance=money(f.reserveBalance-fromReserve);f.reserveUsed=money(f.reserveUsed+fromReserve);due=money(due-fromReserve);paid=money(requested-due);f.totalPayout=money(f.totalPayout+paid);f.openExposure=0;const roundGgr=money(roundStake-paid);if(roundGgr>0&&f.reserveBalance<c.reserveTargetAmount&&f.houseCash>0){const restore=Math.min(c.reserveTargetAmount-f.reserveBalance,roundGgr*c.reserveRestorePct,f.houseCash);if(restore>0){f.houseCash=money(f.houseCash-restore);f.reserveBalance=money(f.reserveBalance+restore);f.reserveRestored=money(f.reserveRestored+restore)}}f.rounds+=1;saveFinance(f);
const m=read(META.metrics,{});m.roomStake=money(num(m.roomStake,0)+roundStake);m.roomPayout=money(num(m.roomPayout,0)+paid);m.simulatedWins=Math.floor(num(m.simulatedWins,0))+wins;m.simulatedLosses=Math.floor(num(m.simulatedLosses,0))+losses;write(META.metrics,m);
const logs=read(META.logs,[]),now=Date.now(),entry={id:'ROOM-'+f.rounds,roundId:'ROOM-'+f.rounds,time:now,timestamp:now,bust:b,bustMultiplier:b,displayMultiplier:b,stake:roundStake,payout:paid,cashout:null,result:paid>roundStake?'ROOM_PAYOUT':'ROOM_GGR',houseCash:f.houseCash,reserve:f.reserveBalance,configVersion:c.configVersion||2,targetRtp:c.targetRtp,simulatedPlayers:bets.length,wins,losses,catchup:!!catchup};logs.push(entry);while(logs.length>250)logs.shift();write(META.logs,logs);write(K.last,{ts:now,rounds:f.rounds});return f}
function freshPlayer(){const p=read(K.presence,null);return !!p&&Date.now()-num(p.ts,0)<PLAYER_FRESH_MS}
function playerBeat(){write(K.presence,{id:ID,ts:Date.now()});write(K.clock,{ts:Date.now()})}
function clearBeat(){const p=read(K.presence,null);if(p?.id===ID)write(K.presence,{id:ID,ts:0})}
function acquire(){const now=Date.now(),l=read(K.lock,null);if(!l||num(l.until,0)<now||l.id===ID){write(K.lock,{id:ID,until:now+LEASE_MS});return read(K.lock,null)?.id===ID}return false}
function status(text,ok=true){if(!IS_ADMIN)return;let el=document.querySelector('[data-continuous-round-status]');if(!el){el=document.createElement('div');el.dataset.continuousRoundStatus='';el.style.cssText='margin-top:5px;font-size:10px;font-weight:900;letter-spacing:.04em;color:#42e58f';const host=document.querySelector('[data-version]')?.parentElement||document.querySelector('.brand')?.parentElement||document.body;host.appendChild(el)}const lang=localStorage.getItem(META.lang)||'az',label=lang==='ru'?'LIVE РАУНДЫ':lang==='en'?'LIVE ROUNDS':'CANLI RAUNDLAR';el.textContent=label+': '+text;el.style.color=ok?'#42e58f':'#ffc54a'}
if(!IS_ADMIN){playerBeat();const beat=setInterval(playerBeat,700);addEventListener('pagehide',()=>{clearInterval(beat);clearBeat()});addEventListener('beforeunload',clearBeat);return}
let nextDue=Date.now()+500,lastReset=localStorage.getItem(META.reset)||'';
function adminTick(){const now=Date.now(),reset=localStorage.getItem(META.reset)||'',cadence=roundMs(cfg());if(reset!==lastReset){lastReset=reset;nextDue=now+250;write(K.clock,{ts:now})}if(freshPlayer()){status('RUNNING · PLAYER ENGINE');nextDue=now+800;return}if(!acquire()){status('RUNNING · SHARED ENGINE');return}const lastClock=read(K.clock,{ts:now}),gap=Math.max(0,now-num(lastClock.ts,now));if(gap>cadence*1.5){const missed=Math.min(120,Math.floor(gap/cadence));for(let i=0;i<missed;i++)runRound(true);write(K.clock,{ts:now})}if(now>=nextDue){const f=runRound(false);write(K.clock,{ts:now});nextDue=now+cadence;status('RUNNING · ROUND #'+f.rounds)}else{const f=finance(cfg());status('RUNNING · ROUND #'+f.rounds)}}
adminTick();setInterval(adminTick,550);
})();