(()=>{'use strict';
const MathCore=globalThis.RCBMathV15,Risk=globalThis.RCBRiskV15;
if(!MathCore||!Risk)throw new Error('RCB v1.5 dependencies missing');
const VERSION='1.5.0',ROOM_ID='ROCKET-CRASH-BEST',APP_ID='az.alekberqasimov.igaming-crash-hub.rocket-crash-best.v15';
const TRYSTERO='https://esm.run/@trystero-p2p/mqtt@0.25.4';
const KEY='rcb.v15.state',WALLET='rcb.v15.wallet',PLAYER='rcb.v15.player';
const listeners=new Set(),peers=new Map();let role='player',selfId='',room=null,connected=false,timer=null,actions={},lastRemoteAt=0;
const now=()=>Date.now(),clone=o=>JSON.parse(JSON.stringify(o)),money=v=>Math.round((Number(v)||0)*100)/100;
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??clone(f)}catch{return clone(f)}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
const uid=p=>p+'-'+(globalThis.crypto?.randomUUID?.()||Math.random().toString(36).slice(2)+Date.now().toString(36)).replace(/[^a-z0-9]/gi,'').slice(0,12).toUpperCase();
function defaultConfig(){return{schemaVersion:15,configRevision:1,mathProfile:{rtp:.97,maxMultiplier:100,testMode:false},minBet:1,maxBet:500,maxPayoutPerBet:50000,maxPayoutPerRound:150000,maxSessionExposure:250000,reserveTargetAmount:100000,usableReservePct:.5,reserveRestorePct:.25,liabilityCoverageEnabled:true,warningCoverage:2,stressCoverage:1.35,criticalCoverage:1.05,growthRate:.145,bettingMs:10000,countdownMs:1800,settledMs:2200,simPlayers:32}}
function normConfig(c={}){const d=defaultConfig(),x={...d,...c};x.schemaVersion=15;x.configRevision=Math.max(1,Math.floor(Number(x.configRevision)||1));x.mathProfile=MathCore.normalizeProfile(x.mathProfile);x.growthRate=Math.min(1,Math.max(.03,Number(x.growthRate)||d.growthRate));x.bettingMs=Math.min(60000,Math.max(3000,Math.round(Number(x.bettingMs)||d.bettingMs)));x.countdownMs=Math.min(10000,Math.max(400,Math.round(Number(x.countdownMs)||d.countdownMs)));x.settledMs=Math.min(10000,Math.max(500,Math.round(Number(x.settledMs)||d.settledMs)));x.simPlayers=Math.min(200,Math.max(0,Math.round(Number(x.simPlayers)||d.simPlayers)));const r=Risk.normalizeConfig(x);Object.assign(x,r);return x}
function freshFinance(c){return{houseCash:0,reserveBalance:c.reserveTargetAmount,openExposure:0,roundExposure:0,sessionExposure:0,totalStake:0,totalPayout:0,rounds:0,reserveUsed:0,reserveRestored:0}}
function freshState(){const c=normConfig(defaultConfig());return{version:VERSION,roomId:ROOM_ID,epoch:1,stateRevision:1,leaderId:null,updatedAt:now(),config:c,pendingConfig:null,finance:freshFinance(c),roundSeq:0,round:null,history:[],audit:[]}}
function sanitize(input){if(!input||typeof input!=='object')return freshState();const c=normConfig(input.config||{}),s={...freshState(),...input,config:c};s.version=VERSION;s.roomId=ROOM_ID;s.epoch=Math.max(1,Math.floor(Number(s.epoch)||1));s.stateRevision=Math.max(1,Math.floor(Number(s.stateRevision)||1));s.roundSeq=Math.max(0,Math.floor(Number(s.roundSeq)||0));s.finance={...freshFinance(c),...(s.finance||{})};for(const k of ['houseCash','reserveBalance','openExposure','roundExposure','sessionExposure','totalStake','totalPayout','reserveUsed','reserveRestored'])s.finance[k]=money(Math.max(0,Number(s.finance[k])||0));s.history=(Array.isArray(s.history)?s.history:[]).filter(h=>Number(h?.roundId)>0&&Number(h?.bust)>=1).slice(-250);s.audit=(Array.isArray(s.audit)?s.audit:[]).slice(-500);if(s.round){s.round={...s.round};s.round.id=Math.max(1,Math.floor(Number(s.round.id)||1));s.round.current=Math.max(1,Number(s.round.current)||1);s.round.realBets=s.round.realBets&&typeof s.round.realBets==='object'?s.round.realBets:{};s.round.simBets=Array.isArray(s.round.simBets)?s.round.simBets:[];if(s.round.bust!=null&&(!Number.isFinite(Number(s.round.bust))||Number(s.round.bust)<1))s.round=null}return s}
let state=sanitize(read(KEY,null));
function audit(type,data={}){state.audit.push({id:uid('AUD'),type,ts:now(),roundId:state.round?.id||null,configRevision:state.config.configRevision,...clone(data)});state.audit=state.audit.slice(-500)}
function persist(){state.updatedAt=now();state.stateRevision=Math.max(1,state.stateRevision+1);write(KEY,state)}
function emit(){persist();const snap=clone(state),meta=getMeta();for(const fn of listeners)try{fn(snap,meta)}catch{};window.dispatchEvent(new CustomEvent('rcb:state',{detail:{state:snap,meta}}));if(isLeader())broadcastState()}
function profile(){let p=read(PLAYER,null);if(!p?.id){p={id:uid('P'),nickname:'Guest-'+Math.floor(1000+Math.random()*9000)};write(PLAYER,p)}return p}
function wallet(){return money(Math.max(0,Number(read(WALLET,{balance:1000}).balance)||0))}
function setWallet(v){write(WALLET,{balance:money(Math.max(0,v))});window.dispatchEvent(new CustomEvent('rcb:wallet',{detail:{balance:wallet()}}))}
function playerPeerCount(){let n=role==='player'?1:0;for(const p of peers.values())if(p.role==='player'&&now()-p.ts<15000)n++;return n}
function candidates(){const a=[];if(role==='player'&&selfId)a.push(selfId);for(const [id,p] of peers)if(p.role==='player'&&now()-p.ts<15000)a.push(id);return a.sort()}
function leaderId(){return candidates()[0]||null}function isLeader(){return role==='player'&&selfId&&leaderId()===selfId}
function getMeta(){return{version:VERSION,roomId:ROOM_ID,role,selfId,leaderId:leaderId(),isLeader:isLeader(),connected,playerPeerCount:playerPeerCount(),adminPeerCount:[...peers.values()].filter(p=>p.role==='admin'&&now()-p.ts<15000).length,lastRemoteAt}}
function riskSnapshot(){return Risk.snapshot(state.finance,state.config)}
const SIM_NAMES=['Araz','Elvin','Murad','Nika','Leo','Emil','Samir','Alex','Rauf','Kenan','Mila','Omar','Lina','Denis','Arif','Tural'];
function makeSimBets(roundId){const out=[],targets=[1.2,1.5,2,2.5,3,5,8],stakes=[1,2,5,10,20,25,50,100];for(let i=0;i<state.config.simPlayers;i++){const stake=stakes[Math.floor(Math.random()*stakes.length)],target=targets[Math.floor(Math.random()*targets.length)];out.push({id:`SIM-${roundId}-${i}`,playerId:`SIM-${i}`,nickname:SIM_NAMES[(roundId+i)%SIM_NAMES.length]+String((roundId*7+i*13)%90+10),stake,target,liability:money(stake*target),status:'OPEN',payout:0,source:'SIM'})}return out}
function applyPending(){if(!state.pendingConfig)return;const n=normConfig(state.pendingConfig);n.configRevision=Math.max(state.config.configRevision+1,n.configRevision);state.config=n;state.pendingConfig=null;audit('CONFIG_APPLIED',{profileId:n.mathProfile.profileId,mathVersion:n.mathProfile.mathVersion})}
function startRound(){applyPending();state.roundSeq=Math.max(state.roundSeq,Number(state.round?.id)||0)+1;state.finance.roundExposure=0;const sim=makeSimBets(state.roundSeq),t=now();state.round={id:state.roundSeq,phase:'BETTING',bettingEnds:t+state.config.bettingMs,countdownEnds:0,startAt:0,settledAt:0,bust:null,current:1,uniform:null,mathProfileId:state.config.mathProfile.profileId,mathVersion:state.config.mathProfile.mathVersion,configRevision:state.config.configRevision,realBets:{},simBets:sim,roomStake:0,roomPayout:0,settlementId:null};for(const b of sim){state.finance.houseCash=money(state.finance.houseCash+b.stake);state.finance.totalStake=money(state.finance.totalStake+b.stake);state.finance.openExposure=money(state.finance.openExposure+b.liability);state.finance.roundExposure=money(state.finance.roundExposure+b.liability);state.finance.sessionExposure=money(state.finance.sessionExposure+b.liability);state.round.roomStake=money(state.round.roomStake+b.stake)}audit('ROUND_OPENED');emit()}
function lockRound(){const r=state.round;if(!r||r.phase!=='BETTING')return;const draw=MathCore.generateBust(state.config.mathProfile);r.bust=draw.bust;r.uniform=draw.uniform;r.phase='COUNTDOWN';r.countdownEnds=now()+state.config.countdownMs;audit('RNG_DRAW',{bust:r.bust,profileId:draw.profile.profileId,mathVersion:draw.profile.mathVersion,uniformRef:Number(draw.uniform.toFixed(12))});emit()}
function currentMultiplier(){const r=state.round;if(!r)return 1;if(r.phase==='RUNNING'){const elapsed=Math.max(0,(now()-r.startAt)/1000);return Math.min(r.bust,Math.max(1,Math.floor(Math.exp(state.config.growthRate*elapsed)*100)/100))}return r.phase==='SETTLED'?r.bust||1:1}
function applyPayout(amount){let rem=money(Math.max(0,amount)),paid=0;let h=Math.min(state.finance.houseCash,rem);state.finance.houseCash=money(state.finance.houseCash-h);rem=money(rem-h);paid=money(paid+h);if(rem>0&&state.config.liabilityCoverageEnabled){const usable=money(state.finance.reserveBalance*state.config.usableReservePct),take=Math.min(usable,rem);state.finance.reserveBalance=money(state.finance.reserveBalance-take);state.finance.reserveUsed=money(state.finance.reserveUsed+take);rem=money(rem-take);paid=money(paid+take)}state.finance.totalPayout=money(state.finance.totalPayout+paid);return paid}
function releaseExposure(b){state.finance.openExposure=money(Math.max(0,state.finance.openExposure-(Number(b.liability)||0)));state.finance.roundExposure=money(Math.max(0,state.finance.roundExposure-(Number(b.liability)||0)));state.finance.sessionExposure=money(Math.max(0,state.finance.sessionExposure-(Number(b.liability)||0)))}
function restoreReserve(){const r=state.round,ggr=Math.max(0,r.roomStake-r.roomPayout),def=Math.max(0,state.config.reserveTargetAmount-state.finance.reserveBalance),mv=Math.min(def,ggr*state.config.reserveRestorePct,state.finance.houseCash);if(mv>0){state.finance.houseCash=money(state.finance.houseCash-mv);state.finance.reserveBalance=money(state.finance.reserveBalance+mv);state.finance.reserveRestored=money(state.finance.reserveRestored+mv)}}
function settleRound(){const r=state.round;if(!r||r.phase==='SETTLED'||r.settlementId)return;r.settlementId=uid('SET');for(const b of r.simBets){if(b.status!=='OPEN')continue;releaseExposure(b);if(b.target<=r.bust){b.payout=applyPayout(Math.min(b.stake*b.target,state.config.maxPayoutPerBet));b.status=b.payout>0?'WON':'UNPAID';r.roomPayout=money(r.roomPayout+b.payout)}else b.status='LOST'}for(const b of Object.values(r.realBets)){if(b.status==='OPEN'){releaseExposure(b);b.status='LOST';b.payout=0;b.settledAt=now()}}r.phase='SETTLED';r.current=r.bust;r.settledAt=now();state.finance.rounds++;restoreReserve();state.history.push({roundId:r.id,bust:r.bust,endedAt:r.settledAt,configRevision:r.configRevision,mathProfileId:r.mathProfileId,mathVersion:r.mathVersion,settlementId:r.settlementId});state.history=state.history.slice(-250);audit('ROUND_SETTLED',{bust:r.bust,settlementId:r.settlementId});emit()}
function acceptBet(req){const r=state.round;if(!r||r.phase!=='BETTING')return{ok:false,reason:'ROUND_CLOSED'};const pid=String(req.playerId||'');if(!pid||r.realBets[pid])return{ok:false,reason:'DUPLICATE_OR_INVALID'};const ev=Risk.evaluateBet({stake:req.stake,maxCashout:req.maxCashout||state.config.maxMultiplier,finance:state.finance,config:state.config});if(ev.decision==='REJECT')return{ok:false,reason:ev.reason,maxAcceptedStake:ev.maxAcceptedStake};const b={playerId:pid,nickname:String(req.nickname||pid).slice(0,24),stake:ev.acceptedStake,autoCashout:Number(req.autoCashout)>=1.01?Number(req.autoCashout):null,maxCashout:ev.maxCashout,liability:ev.liability,status:'OPEN',payout:0,cashout:null,acceptedAt:now(),requestId:req.requestId||uid('REQ'),source:'REAL'};r.realBets[pid]=b;r.roomStake=money(r.roomStake+b.stake);state.finance.houseCash=money(state.finance.houseCash+b.stake);state.finance.totalStake=money(state.finance.totalStake+b.stake);state.finance.openExposure=money(state.finance.openExposure+b.liability);state.finance.roundExposure=money(state.finance.roundExposure+b.liability);state.finance.sessionExposure=money(state.finance.sessionExposure+b.liability);audit('BET_ACCEPTED',{playerId:pid,stake:b.stake,liability:b.liability,decision:ev.decision});emit();return{ok:true,decision:ev.decision,acceptedStake:b.stake,requestId:b.requestId}}
function doCashout(pid){const r=state.round,b=r?.realBets?.[pid];if(!r||r.phase!=='RUNNING'||!b||b.status!=='OPEN')return{ok:false,reason:'NOT_CASHOUTABLE'};const m=currentMultiplier();if(m<1||m>r.bust)return{ok:false,reason:'INVALID_MULTIPLIER'};releaseExposure(b);b.payout=applyPayout(Math.min(b.stake*m,state.config.maxPayoutPerBet));b.cashout=m;b.status=b.payout>0?'CASHED':'UNPAID';b.settledAt=now();r.roomPayout=money(r.roomPayout+b.payout);audit('CASHOUT',{playerId:pid,multiplier:m,payout:b.payout});emit();return{ok:b.payout>0,multiplier:m,payout:b.payout}}
function tick(){if(role!=='player'||!isLeader())return;if(!state.round){startRound();return}const r=state.round,t=now();if(r.phase==='BETTING'&&t>=r.bettingEnds)lockRound();else if(r.phase==='COUNTDOWN'&&t>=r.countdownEnds){r.phase='RUNNING';r.startAt=r.countdownEnds||t;audit('ROUND_RUNNING');emit()}else if(r.phase==='RUNNING'){r.current=currentMultiplier();if(r.current>=r.bust)settleRound()}else if(r.phase==='SETTLED'&&t>=r.settledAt+state.config.settledMs)startRound()}
function proposeConfig(c){const n=normConfig({...state.config,...c});n.configRevision=Math.max(state.config.configRevision+1,Number(c?.configRevision)||0);if(isLeader()){state.pendingConfig=n;audit('CONFIG_PROPOSED',{nextRevision:n.configRevision});emit();return true}if(actions.config){actions.config.send({config:n,ts:now()}).catch?.(()=>{});return true}state.pendingConfig=n;persist();return false}
function reconcileWallet(){const p=profile(),r=state.round,b=r?.realBets?.[p.id];if(!b)return;const k=`rcb.v15.journal.${r.id}.${p.id}`,j=read(k,{debited:false,credited:false});let w=wallet(),changed=false;if(!j.debited){w=money(w-b.stake);j.debited=true;changed=true}if(['CASHED','WON'].includes(b.status)&&b.payout>0&&!j.credited){w=money(w+b.payout);j.credited=true;changed=true}if(changed){write(k,j);setWallet(w)}}
function placeBet(stake,autoCashout=null){const p=profile(),req={requestId:uid('REQ'),playerId:p.id,nickname:p.nickname,stake:money(stake),autoCashout,maxCashout:autoCashout||state.config.maxMultiplier,ts:now()};if(wallet()<req.stake)return{ok:false,reason:'BALANCE'};if(isLeader())return acceptBet(req);actions.bet?.send(req).catch?.(()=>{});return{ok:true,pending:true,requestId:req.requestId}}
function cashout(){const p=profile();if(isLeader())return doCashout(p.id);actions.cash?.send({playerId:p.id,ts:now()}).catch?.(()=>{});return{ok:true,pending:true}}
function broadcastPresence(){actions.presence?.send({role,ts:now(),profile:role==='player'?profile():null}).catch?.(()=>{})}
function broadcastState(target){if(!isLeader()||!actions.state)return;state.leaderId=selfId;actions.state.send({state:clone(state),ts:now()},target?{target}:undefined).catch?.(()=>{})}
function adopt(packet,peerId){if(peerId!==leaderId())return;const incoming=sanitize(packet?.state);const newer=incoming.epoch>state.epoch||(incoming.epoch===state.epoch&&incoming.stateRevision>state.stateRevision);if(!newer)return;state=incoming;lastRemoteAt=now();write(KEY,state);const snap=clone(state),meta=getMeta();for(const fn of listeners)try{fn(snap,meta)}catch{}}
async function connect(){try{const mod=await import(TRYSTERO);selfId=mod.selfId||uid('PEER');room=mod.joinRoom({appId:APP_ID},ROOM_ID);for(const n of ['presence','state','bet','cash','config','hello'])actions[n]=room.makeAction(n+'15');actions.presence.onMessage=(d,{peerId}={})=>{if(!peerId)return;peers.set(peerId,{role:d?.role||'unknown',ts:now()});if(isLeader())broadcastState(peerId)};actions.state.onMessage=(d,{peerId}={})=>adopt(d,peerId);actions.bet.onMessage=(d)=>{if(isLeader())acceptBet(d)};actions.cash.onMessage=(d)=>{if(isLeader())doCashout(String(d?.playerId||''))};actions.config.onMessage=(d)=>{if(isLeader()&&d?.config)proposeConfig(d.config)};room.onPeerJoin=pid=>{peers.set(pid,{role:'unknown',ts:now()});broadcastPresence();setTimeout(()=>{if(isLeader())broadcastState(pid)},500)};room.onPeerLeave=pid=>{peers.delete(pid);if(isLeader()){state.epoch++;audit('LEADER_EPOCH',{epoch:state.epoch});emit()}};connected=true;broadcastPresence();setInterval(()=>{for(const [id,p] of peers)if(now()-p.ts>20000)peers.delete(id);broadcastPresence();if(isLeader())broadcastState()},1000)}catch(e){connected=false;selfId=selfId||uid(role==='admin'?'ADMIN':'SOLO');console.warn('[RCB] P2P unavailable, solo demo mode',e)}}
function subscribe(fn){listeners.add(fn);try{fn(clone(state),getMeta())}catch{}return()=>listeners.delete(fn)}
function start(opts={}){role=opts.role==='admin'?'admin':'player';selfId=uid(role==='admin'?'ADMIN':'PLAYER');connect();clearInterval(timer);timer=setInterval(()=>{tick();if(role==='player')reconcileWallet()},80);if(role==='player'&&!state.round)startRound();else emit();return api}
const api={VERSION,ROOM_ID,start,subscribe,getState:()=>clone(state),getMeta,profile,wallet,setWallet,placeBet,cashout,proposeConfig,currentMultiplier,riskSnapshot,mathProfile:()=>clone(state.config.mathProfile)};
globalThis.RocketCrashBest=api;
})();
