(()=>{'use strict';
const VERSION='1.4.0',ROOM_ID='SONIC-CRASH-BEST',APP_ID='az.alekberqasimov.igaming-crash-hub.sonic-crash-best.v14';
const STATE_KEY='scb.v14.state',WALLET_KEY='scb.v14.wallet',PLAYER_KEY='scb.v14.player',TRYSTERO='https://esm.run/@trystero-p2p/mqtt@0.25.4';
const listeners=new Set(),peers=new Map();let role='player',selfId='',room=null,aPresence=null,aState=null,aBet=null,aCash=null,aConfig=null,aHello=null,timer=null,connected=false,lastRemoteAt=0;
const now=()=>Date.now(),clone=o=>JSON.parse(JSON.stringify(o)),clamp=(v,a,b,f=a)=>{v=Number(v);return Number.isFinite(v)?Math.min(b,Math.max(a,v)):f},money=v=>Math.round((Number(v)||0)*100)/100;
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??clone(f)}catch{return clone(f)}};const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
function validMult(v){const n=Number(v);return Number.isFinite(n)&&n>=1?Math.floor(n*100)/100:null}
function secure(){if(globalThis.crypto?.getRandomValues){const a=new Uint32Array(1);crypto.getRandomValues(a);return(a[0]+1)/4294967297}return Math.random()||Number.EPSILON}
function id(prefix='X'){return prefix+'-'+(crypto?.randomUUID?.()||Math.random().toString(36).slice(2)+Date.now().toString(36)).replace(/[^a-z0-9]/gi,'').slice(0,12).toUpperCase()}
function defaultConfig(){return{schemaVersion:14,configRevision:1,targetProfitMargin:.07,targetRtp:.93,payoutBudgetPct:.50,minBet:1,maxBet:500,maxMultiplier:100,maxPayoutPerBet:50000,maxPayoutPerRound:150000,maxSessionExposure:250000,growthRate:.145,bettingMs:10000,countdownMs:1800,settledMs:2200,reserveTargetAmount:20000,usableReservePct:1,reserveRestorePct:.25,liabilityCoverageEnabled:true,riskThresholds:{warningCoverage:2,stressCoverage:1.35,criticalCoverage:1.05},riskPressure:{reserveWeight:.45,marginWeight:.35,budgetWeight:.20,coverageWeight:.35,maxRtpReduction:.70}}}
function normConfig(c){const d=defaultConfig(),x=Object.assign({},d,c||{});x.schemaVersion=14;x.configRevision=Math.max(1,Math.floor(Number(x.configRevision)||1));x.targetProfitMargin=clamp(x.targetProfitMargin,.01,.95,d.targetProfitMargin);x.targetRtp=1-x.targetProfitMargin;x.payoutBudgetPct=clamp(x.payoutBudgetPct,.05,1,d.payoutBudgetPct);x.minBet=clamp(x.minBet,.01,1e6,d.minBet);x.maxBet=clamp(x.maxBet,x.minBet,1e8,d.maxBet);x.maxMultiplier=clamp(x.maxMultiplier,2,1e5,d.maxMultiplier);x.maxPayoutPerBet=clamp(x.maxPayoutPerBet,x.minBet,1e12,d.maxPayoutPerBet);x.maxPayoutPerRound=clamp(x.maxPayoutPerRound,x.maxPayoutPerBet,1e13,d.maxPayoutPerRound);x.maxSessionExposure=clamp(x.maxSessionExposure,x.maxPayoutPerRound,1e14,d.maxSessionExposure);x.growthRate=clamp(x.growthRate,.03,1,d.growthRate);x.bettingMs=Math.round(clamp(x.bettingMs,3000,60000,d.bettingMs));x.countdownMs=Math.round(clamp(x.countdownMs,400,10000,d.countdownMs));x.settledMs=Math.round(clamp(x.settledMs,500,10000,d.settledMs));x.reserveTargetAmount=clamp(x.reserveTargetAmount,0,1e12,d.reserveTargetAmount);x.usableReservePct=clamp(x.usableReservePct,0,1,d.usableReservePct);x.reserveRestorePct=clamp(x.reserveRestorePct,0,1,d.reserveRestorePct);x.liabilityCoverageEnabled=x.liabilityCoverageEnabled!==false;x.riskThresholds=Object.assign({},d.riskThresholds,x.riskThresholds||{});x.riskPressure=Object.assign({},d.riskPressure,x.riskPressure||{});return x}
function newFinance(c){return{houseCash:0,reserveBalance:c.reserveTargetAmount,totalStake:0,totalPayout:0,rounds:0,openExposure:0,reserveUsed:0,reserveRestored:0}}
function initialState(){const c=defaultConfig(),old=read(STATE_KEY,null),seq=Math.max(0,Number(old?.roundSeq)||0,Number(old?.round?.id)||0);return{version:VERSION,roomId:ROOM_ID,epoch:1,leaderId:null,updatedAt:now(),config:normConfig(old?.config||c),pendingConfig:old?.pendingConfig?normConfig(old.pendingConfig):null,finance:old?.finance?Object.assign(newFinance(c),old.finance):newFinance(c),roundSeq:seq,round:null,history:Array.isArray(old?.history)?old.history.filter(h=>validMult(h?.bust)!==null).slice(-200):[],players:{}}}
let state=initialState();
function sanitizeState(s){if(!s||typeof s!=='object')return null;const x=clone(s);x.version=VERSION;x.roomId=ROOM_ID;x.config=normConfig(x.config);x.pendingConfig=x.pendingConfig?normConfig(x.pendingConfig):null;x.finance=Object.assign(newFinance(x.config),x.finance||{});x.finance.houseCash=Math.max(0,Number(x.finance.houseCash)||0);x.finance.reserveBalance=Math.max(0,Number(x.finance.reserveBalance)||0);x.finance.totalStake=Math.max(0,Number(x.finance.totalStake)||0);x.finance.totalPayout=Math.max(0,Number(x.finance.totalPayout)||0);x.finance.openExposure=Math.max(0,Number(x.finance.openExposure)||0);x.roundSeq=Math.max(0,Math.floor(Number(x.roundSeq)||0));x.history=(Array.isArray(x.history)?x.history:[]).map(h=>{const b=validMult(h?.bust),rid=Math.floor(Number(h?.roundId)||0);return b!==null&&rid>0?{roundId:rid,bust:b,endedAt:Number(h.endedAt)||0,configRevision:Number(h.configRevision)||1}:null}).filter(Boolean).sort((a,b)=>a.roundId-b.roundId).slice(-200);x.players=x.players&&typeof x.players==='object'?x.players:{};if(x.round){const r=x.round;r.id=Math.max(1,Math.floor(Number(r.id)||1));r.bust=r.bust==null?null:validMult(r.bust);r.current=Math.max(1,Number(r.current)||1);r.realBets=r.realBets&&typeof r.realBets==='object'?r.realBets:{};r.simBets=Array.isArray(r.simBets)?r.simBets:[];if(r.bust===null&&(r.phase==='COUNTDOWN'||r.phase==='RUNNING'||r.phase==='SETTLED'))return null}return x}
function persist(){state.updatedAt=now();write(STATE_KEY,state)}
function emit(){persist();for(const fn of listeners)try{fn(clone(state),getMeta())}catch{};window.dispatchEvent(new CustomEvent('scb:state',{detail:{state:clone(state),meta:getMeta()}}))}
function playerProfile(){try{const p=window.IGCHPlayer?.getProfile?.();if(p?.id)return{id:String(p.id),nickname:String(p.nickname||p.id)}}catch{}let p=read(PLAYER_KEY,null);if(!p?.id){p={id:id('P'),nickname:'Guest-'+Math.floor(1000+secure()*9000)};write(PLAYER_KEY,p)}return p}
function wallet(){return Math.max(0,Number(read(WALLET_KEY,{balance:1000}).balance)||0)}function setWallet(v){write(WALLET_KEY,{balance:money(Math.max(0,v))});window.dispatchEvent(new CustomEvent('scb:wallet',{detail:{balance:wallet()}}))}
function riskSnapshot(s=state,cfg=state.config,extra=0){const f=s.finance,target=Math.max(0,cfg.reserveTargetAmount),rb=Math.max(0,Number(f.reserveBalance)||0),reserveHealth=target?clamp(rb/target,0,1,1):1,profit=f.totalStake-f.totalPayout,actualMargin=f.totalStake?profit/f.totalStake:cfg.targetProfitMargin,handle=Math.min(1,f.totalStake/5000),marginDeficit=Math.max(0,cfg.targetProfitMargin-actualMargin),marginPressure=Math.min(1,(marginDeficit/Math.max(.08,cfg.targetProfitMargin*.5))*handle),budget=Math.max(0,f.houseCash*cfg.payoutBudgetPct),exposure=Math.max(0,f.openExposure+extra),budgetPressure=exposure?clamp(1-budget/exposure,0,1,0):0,reservePressure=1-reserveHealth,rp=cfg.riskPressure,base=clamp(reservePressure*rp.reserveWeight+marginPressure*rp.marginWeight+budgetPressure*rp.budgetWeight,0,1,0),liq=Math.max(0,f.houseCash)+rb*cfg.usableReservePct,coverage=exposure?liq/exposure:999;let cp=0;if(cfg.liabilityCoverageEnabled&&exposure){const w=Math.max(Number(cfg.riskThresholds.warningCoverage)||2,(Number(cfg.riskThresholds.criticalCoverage)||1.05)+.01),cr=Math.max(.01,Number(cfg.riskThresholds.criticalCoverage)||1.05);if(coverage<=cr)cp=1;else if(coverage<w)cp=clamp((w-coverage)/(w-cr),0,1,0)}const pressure=clamp(base+(cfg.liabilityCoverageEnabled?cp*Number(rp.coverageWeight||.35)*(1-base):0),0,1,0),effectiveRtp=Math.max(.05,cfg.targetRtp*(1-pressure*Number(rp.maxRtpReduction||.70)));return{reserveHealth,actualMargin,budget,exposure,coverage,pressure,effectiveRtp,availableLiquidity:liq}}
function generateBust(){const s=riskSnapshot(),u=secure();let x=s.effectiveRtp/(1-u);x=clamp(x,1,state.config.maxMultiplier,1);if(s.pressure>.35&&x<1.01)x=Math.min(state.config.maxMultiplier,1.01+secure()*(.11-.06*s.pressure));return validMult(x)??1}
const NAMES=['Araz','Elvin','Murad','Nika','Leo','Emil','Samir','Alex','Rauf','Kenan','Mila','Omar','Lina','Denis','Arif','Tural','Nina','Rashad','Ilya','Max'];
function makeSimBets(roundId){const out=[],count=24+Math.floor(secure()*27),targets=[1.2,1.3,1.5,1.8,2,2.5,3,5,8],stakes=[1,2,5,10,10,20,25,50,100];for(let i=0;i<count;i++){const target=targets[Math.floor(secure()*targets.length)],stake=Math.min(state.config.maxBet,stakes[Math.floor(secure()*stakes.length)]),liability=money(stake*target);out.push({id:'SIM-'+roundId+'-'+i,name:NAMES[(i+roundId)%NAMES.length]+String((i*17+roundId)%90+10),stake,target,liability,payout:0,status:'OPEN'})}return out}
function transfer(amount){amount=money(Math.max(0,amount));let h=Math.min(state.finance.houseCash,amount);state.finance.houseCash=money(state.finance.houseCash-h);let rem=money(amount-h),r=Math.min(state.finance.reserveBalance*state.config.usableReservePct,rem);state.finance.reserveBalance=money(state.finance.reserveBalance-r);state.finance.reserveUsed=money((state.finance.reserveUsed||0)+r);rem=money(rem-r);const paid=money(amount-rem);state.finance.totalPayout=money(state.finance.totalPayout+paid);return paid}
function applyPendingConfig(){if(!state.pendingConfig)return;const next=normConfig(state.pendingConfig);next.configRevision=Math.max(state.config.configRevision+1,next.configRevision);state.config=next;state.pendingConfig=null}
function startRound(){applyPendingConfig();state.roundSeq=Math.max(state.roundSeq,Number(state.round?.id)||0)+1;const t=now(),sim=makeSimBets(state.roundSeq);state.round={id:state.roundSeq,phase:'BETTING',bettingEnds:t+state.config.bettingMs,countdownEnds:0,startAt:0,settledAt:0,bust:null,current:1,configRevision:state.config.configRevision,simBets:sim,realBets:{},roomStake:0,roomPayout:0};for(const b of sim){state.finance.houseCash=money(state.finance.houseCash+b.stake);state.finance.totalStake=money(state.finance.totalStake+b.stake);state.finance.openExposure=money(state.finance.openExposure+b.liability);state.round.roomStake=money(state.round.roomStake+b.stake)}emit()}
function lockRound(){if(!state.round||state.round.phase!=='BETTING')return;state.round.bust=generateBust();state.round.phase='COUNTDOWN';state.round.countdownEnds=now()+state.config.countdownMs;emit()}
function currentMultiplier(){const r=state.round;if(!r)return 1;if(r.phase==='RUNNING'){const elapsed=Math.max(0,(now()-r.startAt)/1000),m=Math.exp(state.config.growthRate*elapsed);return Math.min(r.bust||1,Math.max(1,Math.floor(m*100)/100))}if(r.phase==='SETTLED')return r.bust||1;return 1}
function restoreReserve(){const r=state.round;if(!r)return;const ggr=Math.max(0,r.roomStake-r.roomPayout),def=Math.max(0,state.config.reserveTargetAmount-state.finance.reserveBalance),mv=Math.min(def,ggr*state.config.reserveRestorePct,state.finance.houseCash);if(mv>0){state.finance.houseCash=money(state.finance.houseCash-mv);state.finance.reserveBalance=money(state.finance.reserveBalance+mv);state.finance.reserveRestored=money((state.finance.reserveRestored||0)+mv)}}
function settleRound(){const r=state.round;if(!r||r.phase==='SETTLED')return;const bust=validMult(r.bust);if(bust===null){console.error('[SCB] invalid bust rejected',r.bust);r.bust=1}else r.bust=bust;let roundPayout=0;for(const b of r.simBets){if(b.status!=='OPEN')continue;state.finance.openExposure=money(Math.max(0,state.finance.openExposure-b.liability));if(b.target<=r.bust){const paid=transfer(Math.min(b.stake*b.target,state.config.maxPayoutPerBet));b.payout=paid;b.status=paid>0?'WON':'UNPAID';roundPayout=money(roundPayout+paid)}else b.status='LOST'}for(const b of Object.values(r.realBets)){if(b.status==='OPEN'){state.finance.openExposure=money(Math.max(0,state.finance.openExposure-b.liability));b.status='LOST';b.payout=0;b.settledAt=now()}}
r.roomPayout=money(r.roomPayout+roundPayout);r.phase='SETTLED';r.current=r.bust;r.settledAt=now();state.finance.rounds++;restoreReserve();state.history.push({roundId:r.id,bust:r.bust,endedAt:r.settledAt,configRevision:r.configRevision});state.history=state.history.slice(-200);emit()}
function tickLeader(){if(role!=='player'||!isLeader())return;if(!state.round){startRound();return}const r=state.round,t=now();if(r.phase==='BETTING'&&t>=r.bettingEnds)lockRound();else if(r.phase==='COUNTDOWN'&&t>=r.countdownEnds){r.phase='RUNNING';r.startAt=r.countdownEnds||t;emit()}else if(r.phase==='RUNNING'){r.current=currentMultiplier();if(r.current>=r.bust)settleRound();else if(t%250<80)emit()}else if(r.phase==='SETTLED'&&t>=r.settledAt+state.config.settledMs)startRound()}
function maxStake(stake){const c=state.config,s=riskSnapshot(),exposure=Math.min(c.maxPayoutPerBet,stake*c.maxMultiplier),roundHead=Math.max(0,c.maxPayoutPerRound-state.finance.openExposure),sessionHead=Math.max(0,c.maxSessionExposure-state.finance.openExposure);let allowed=Math.min(c.maxBet,roundHead/c.maxMultiplier,sessionHead/c.maxMultiplier);if(c.liabilityCoverageEnabled){const cr=Math.max(.01,Number(c.riskThresholds.criticalCoverage)||1.05),head=Math.max(0,s.availableLiquidity/cr-state.finance.openExposure);allowed=Math.min(allowed,head/c.maxMultiplier)}return Math.max(0,allowed)}
function leaderAcceptBet(req,peerId){const r=state.round,c=state.config;if(!r||r.phase!=='BETTING')return false;const stake=money(Number(req.stake));if(!Number.isFinite(stake)||stake<c.minBet||stake>maxStake(stake))return false;const pid=String(req.playerId||'');if(!pid||r.realBets[pid])return false;const liability=money(Math.min(c.maxPayoutPerBet,stake*c.maxMultiplier));r.realBets[pid]={playerId:pid,nickname:String(req.nickname||pid).slice(0,24),stake,autoCashout:Number(req.autoCashout)>=1.01?Number(req.autoCashout):null,liability,status:'OPEN',payout:0,cashout:null,acceptedAt:now(),requestId:req.requestId||id('REQ')};r.roomStake=money(r.roomStake+stake);state.finance.houseCash=money(state.finance.houseCash+stake);state.finance.totalStake=money(state.finance.totalStake+stake);state.finance.openExposure=money(state.finance.openExposure+liability);emit();return true}
function leaderCashout(req){const r=state.round;if(!r||r.phase!=='RUNNING')return false;const b=r.realBets[String(req.playerId||'')];if(!b||b.status!=='OPEN')return false;const m=currentMultiplier();if(m<1||m>r.bust)return false;state.finance.openExposure=money(Math.max(0,state.finance.openExposure-b.liability));const paid=transfer(Math.min(b.stake*m,state.config.maxPayoutPerBet));b.cashout=m;b.payout=paid;b.status='CASHED';b.settledAt=now();r.roomPayout=money(r.roomPayout+paid);emit();return true}
function proposeConfig(cfg){const x=normConfig(cfg);x.configRevision=Math.max(state.config.configRevision+1,x.configRevision||0);if(role==='player'&&isLeader()){state.pendingConfig=x;emit();broadcastState();return true}if(aConfig){try{aConfig.send({type:'CONFIG',config:x,ts:now()}).catch?.(()=>{});return true}catch{}}state.pendingConfig=x;persist();return false}
function getCandidateIds(){const ids=[];if(role==='player'&&selfId)ids.push(selfId);for(const [pid,p] of peers)if(p.role==='player'&&now()-p.ts<15000)ids.push(pid);return ids.sort()}
function leaderId(){return getCandidateIds()[0]||((role==='player'&&selfId)?selfId:null)}function isLeader(){return role==='player'&&!!selfId&&leaderId()===selfId}
function getMeta(){return{version:VERSION,roomId:ROOM_ID,role,selfId,leaderId:leaderId(),isLeader:isLeader(),connected,peerCount:[...peers.values()].filter(p=>now()-p.ts<15000).length,lastRemoteAt}}
function broadcastPresence(){if(!aPresence)return;try{aPresence.send({role,ts:now(),profile:role==='player'?playerProfile():null}).catch?.(()=>{})}catch{}}
function broadcastState(target=null){if(!aState||!isLeader())return;state.leaderId=selfId;state.updatedAt=now();const p={state:clone(state),ts:now()};try{aState.send(p,target?{target}:undefined).catch?.(()=>{})}catch{}}
function adoptRemote(packet,peerId){if(peerId!==leaderId())return;const s=sanitizeState(packet?.state);if(!s)return;state=s;lastRemoteAt=now();persist();for(const fn of listeners)try{fn(clone(state),getMeta())}catch{};window.dispatchEvent(new CustomEvent('scb:state',{detail:{state:clone(state),meta:getMeta()}}))}
async function connect(){try{const mod=await import(TRYSTERO);selfId=mod.selfId||id('PEER');room=mod.joinRoom({appId:APP_ID},ROOM_ID);aPresence=room.makeAction('presence14');aState=room.makeAction('state14');aBet=room.makeAction('bet14');aCash=room.makeAction('cash14');aConfig=room.makeAction('config14');aHello=room.makeAction('hello14');aPresence.onMessage=(d,{peerId}={})=>{if(!peerId||!d)return;peers.set(peerId,{role:d.role||'player',ts:now(),profile:d.profile||null});broadcastPresence();if(isLeader())broadcastState(peerId)};aState.onMessage=(d,{peerId}={})=>adoptRemote(d,peerId);aBet.onMessage=(d)=>{if(isLeader())leaderAcceptBet(d)};aCash.onMessage=(d)=>{if(isLeader())leaderCashout(d)};aConfig.onMessage=(d)=>{if(isLeader()&&d?.config){state.pendingConfig=normConfig(d.config);state.pendingConfig.configRevision=Math.max(state.config.configRevision+1,state.pendingConfig.configRevision);emit();broadcastState()}};aHello.onMessage=(_d,{peerId}={})=>{if(isLeader())broadcastState(peerId)};room.onPeerJoin=pid=>{peers.set(pid,{role:'unknown',ts:now()});broadcastPresence();try{aHello.send({role,ts:now()},{target:pid}).catch?.(()=>{})}catch{};setTimeout(()=>{if(isLeader())broadcastState(pid)},250)};room.onPeerLeave=pid=>{peers.delete(pid);if(isLeader()){state.epoch=(Number(state.epoch)||1)+1;state.leaderId=selfId;emit();broadcastState()}};connected=true;broadcastPresence();setInterval(()=>{for(const [k,p] of peers)if(now()-p.ts>20000)peers.delete(k);broadcastPresence();if(isLeader())broadcastState()},1000)}catch(e){connected=false;selfId=selfId||id('SOLO');console.warn('[SCB room offline; solo mode]',e)}}
function placeBet(stake,autoCashout=null){const p=playerProfile(),r=state.round,c=state.config;if(!r||r.phase!=='BETTING')return{ok:false,reason:'ROUND_CLOSED'};stake=money(Number(stake));if(!Number.isFinite(stake)||stake<c.minBet||stake>maxStake(stake))return{ok:false,reason:'STAKE_LIMIT'};if(wallet()<stake)return{ok:false,reason:'BALANCE'};const req={requestId:id('REQ'),playerId:p.id,nickname:p.nickname,stake,autoCashout:Number(autoCashout)>=1.01?Number(autoCashout):null,ts:now()};if(isLeader()){const ok=leaderAcceptBet(req,selfId);return{ok,requestId:req.requestId}}try{aBet?.send(req).catch?.(()=>{})}catch{}return{ok:true,pending:true,requestId:req.requestId}}
function cashout(){const p=playerProfile();if(isLeader())return leaderCashout({playerId:p.id,ts:now()});try{aCash?.send({playerId:p.id,ts:now()}).catch?.(()=>{});return true}catch{return false}}
function reconcileWallet(){const p=playerProfile(),r=state.round;if(!r)return;const b=r.realBets?.[p.id];if(!b)return;const key='scb.v14.journal.'+r.id+'.'+p.id,j=read(key,{debited:false,credited:false});let w=wallet(),changed=false;if(!j.debited){w=money(w-b.stake);j.debited=true;changed=true}if((b.status==='CASHED'||b.status==='WON')&&!j.credited&&b.payout>0){w=money(w+b.payout);j.credited=true;changed=true}if(changed){write(key,j);setWallet(w)}}
function subscribe(fn){listeners.add(fn);try{fn(clone(state),getMeta())}catch{};return()=>listeners.delete(fn)}
function start(opts={}){role=opts.role==='admin'?'admin':'player';state=sanitizeState(read(STATE_KEY,state))||state;if(role==='player'&&!state.round)startRound();selfId=id(role==='admin'?'ADMIN':'PLAYER');connect();clearInterval(timer);timer=setInterval(()=>{if(role==='player'){tickLeader();reconcileWallet()}},80);emit();return api}
const api={VERSION,ROOM_ID,start,subscribe,getState:()=>clone(state),getMeta,playerProfile,wallet,setWallet,placeBet,cashout,proposeConfig,riskSnapshot:()=>riskSnapshot(),currentMultiplier,maxStake:()=>maxStake(state.config.minBet),validMult,defaultConfig,normConfig};window.SonicCrashBest=api;
})();